---
name: CI
# yamllint disable-line rule:truthy
on:
  [push, workflow_dispatch]

jobs:
  flavourMainline:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout flavourLTS Repo'
        uses: actions/checkout@v4

      - name: Get version
        run: |
         VERSION=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
         REL=$(egrep ^PKGREL build.sh|cut -d= -f2)
         echo "ver=${VERSION}" >> $GITHUB_ENV
         echo "release=${REL}" >> $GITHUB_ENV
          
      - name: 'Checkout flavourMainline Repo'
        uses: actions/checkout@v4
        with:
          ref: flavourMainline
          persist-credentials: false

      - name: 'Push new version to flavourMainline'
        id: publish
        run: |
         sed -i "s/KERNEL_VERSION=6.*/KERNEL_VERSION=${{ env.ver }}/g" build.sh
         sed -i '/^PKGREL=/ s/PKGREL=[0-9]*/PKGREL=${{ env.release }}/' build.sh
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git commit -m "${{ env.ver }}-${{ env.release }}" -a
      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: flavourMainline

  ISO-Kubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Generate Tag
        id: tag
        run: |
          VER=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
          REL=$(egrep ^PKGREL build.sh|cut -d= -f2)
          echo Version is ${VER}-${REL}
          echo "kver=${VER}" >> $GITHUB_ENV
          echo "isotag=${VER}-${REL}" >> $GITHUB_ENV
  
      - name: Run build script
        run: |
          chmod +x ${{ github.workspace }}/build_in_docker.sh
          ${{ github.workspace }}/build_in_docker.sh kubuntu

      - name: print sha256sum
        run: |
          cat ${{ github.workspace }}/output/sha256*
          SHA256=$(cat ${{ github.workspace }}/output/sha256* | cut -d " " -f 1)
          echo "sha256=${SHA256}" >> $GITHUB_ENV
  
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubuntu-24.04
          path: ${{ github.workspace }}/output/*.iso

      - name: Remove unsplit ISO
        run: |
          sudo rm ${{ github.workspace }}/output/*.iso

      - name: Release
        if: github.ref == 'refs/heads/flavourLTS'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/output/*
          tag_name: v${{ env.isotag }}
          #body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the json
        if: github.ref == 'refs/heads/flavourLTS'
        run: |
          git clone https://github.com/t2linux/wiki.git
          cd wiki/docs/tools

          cat << EOF > update.py
          import json
          # Define the new links
          new_link1 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/kubuntu-24.04-${{ env.kver }}-t2-noble.iso.00"
          new_link2 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/kubuntu-24.04-${{ env.kver }}-t2-noble.iso.01"
          new_link3 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/kubuntu-24.04-${{ env.kver }}-t2-noble.iso.02"
          # Load the JSON file
          with open('distro-metadata.json', 'r') as file:
              data = json.load(file)
          # Function to update the links
          def update_links(distros, name, new_links, sha256):
              for distro in distros:
                  if distro['name'] == name:
                      distro['iso'] = new_links
                      distro['sha256'] = sha256
          # Update the links
          update_links(data['all'], "Kubuntu 24.04 - Noble Numbat", [new_link1, new_link2, new_link3], "${{ env.sha256 }}")
          # Save the updated JSON back to the file
          with open('distro-metadata.json', 'w') as file:
              json.dump(data, file, indent=2)
          print("Links updated successfully.")
          EOF

          python3 update.py
          rm update.py
          cd -

      - name: Push updated links to t2linux.org
        if: github.ref == 'refs/heads/flavourLTS'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'wiki'
          destination-github-username: 't2linux'
          destination-repository-name: 'wiki'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: master
          commit-message: Distro metadata - Update Kubuntu 24.04 to v${{ env.isotag }}

  ISO-Ubuntu-unity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Generate Tag
        id: tag
        run: |
          VER=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
          REL=$(egrep ^PKGREL build.sh|cut -d= -f2)
          echo Version is ${VER}-${REL}
          echo "kver=${VER}" >> $GITHUB_ENV
          echo "isotag=${VER}-${REL}" >> $GITHUB_ENV
  
      - name: Run build script
        run: |
          chmod +x ${{ github.workspace }}/build_in_docker.sh
          ${{ github.workspace }}/build_in_docker.sh ubuntu-unity

      - name: print sha256sum
        run: |
          cat ${{ github.workspace }}/output/sha256*
          SHA256=$(cat ${{ github.workspace }}/output/sha256* | cut -d " " -f 1)
          echo "sha256=${SHA256}" >> $GITHUB_ENV
  
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu-Unity-24.04
          path: ${{ github.workspace }}/output/*.iso

      - name: Remove unsplit ISO
        run: |
          sudo rm ${{ github.workspace }}/output/*.iso

      - name: Release
        if: github.ref == 'refs/heads/flavourLTS'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/output/*
          tag_name: v${{ env.isotag }}
          #body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the json
        if: github.ref == 'refs/heads/flavourLTS'
        run: |
          git clone https://github.com/t2linux/wiki.git
          cd wiki/docs/tools

          cat << EOF > update.py
          import json
          # Define the new links
          new_link1 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-unity-24.04-${{ env.kver }}-t2-noble.iso.00"
          new_link2 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-unity-24.04-${{ env.kver }}-t2-noble.iso.01"
          new_link3 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-unity-24.04-${{ env.kver }}-t2-noble.iso.02"
          # Load the JSON file
          with open('distro-metadata.json', 'r') as file:
              data = json.load(file)
          # Function to update the links
          def update_links(distros, name, new_links, sha256):
              for distro in distros:
                  if distro['name'] == name:
                      distro['iso'] = new_links
                      distro['sha256'] = sha256
          # Update the links
          update_links(data['all'], "Ubuntu Unity 24.04 - Noble Numbat", [new_link1, new_link2, new_link3], "${{ env.sha256 }}" )
          # Save the updated JSON back to the file
          with open('distro-metadata.json', 'w') as file:
              json.dump(data, file, indent=2)
          print("Links updated successfully.")
          EOF

          python3 update.py
          rm update.py
          cd -

      - name: Push updated links to t2linux.org
        if: github.ref == 'refs/heads/flavourLTS'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'wiki'
          destination-github-username: 't2linux'
          destination-repository-name: 'wiki'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: master
          commit-message: Distro metadata - Update Ubuntu Unity 24.04 to v${{ env.isotag }}
