---
name: CI
# yamllint disable-line rule:truthy
on:
  [push, workflow_dispatch]

jobs:
  ISO:
    strategy:
      matrix:
        target:
          - image: ubuntu
          - image: kubuntu
          #- image: ubuntu-unity

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Generate Tag
        id: tag
        run: |
          VER=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
          REL=$(egrep ^PKGREL build.sh|cut -d= -f2)
          echo Version is ${VER}-${REL}
          echo "kver=${VER}" >> $GITHUB_ENV
          echo "isotag=${VER}-${REL}" >> $GITHUB_ENV
          CAPS=$(echo "${{ matrix.target.image }}" | tr '_-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}')
          echo "caps=${CAPS}" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x ${{ github.workspace }}/build_in_docker.sh
          ${{ github.workspace }}/build_in_docker.sh ${{ matrix.target.image }}

      - name: print sha256sum
        run: |
          cat ${{ github.workspace }}/output/sha256*
          SHA256=$(cat ${{ github.workspace }}/output/sha256* | cut -d " " -f 1)
          echo "sha256=${SHA256}" >> $GITHUB_ENV
 
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: ISO-${{ matrix.target.image }}
          path: ${{ github.workspace }}/output/${{ matrix.target.image }}-25.10-${{ env.kver }}-t2-questing.iso
          archive: false

      - name: Remove unsplit ISO
        run: |
          sudo rm ${{ github.workspace }}/output/*.iso
      - name: Release
        if: github.ref == 'refs/heads/mainline'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/output/*
          tag_name: v${{ env.isotag }}
          #body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the json
        if: github.ref == 'refs/heads/mainline'
        run: |
          git clone https://github.com/t2linux/wiki.git
          cd wiki/docs/tools

          cat << EOF > update.py
          import json
          # Define the new links
          new_link1 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/${{ matrix.target.image }}-25.10-${{ env.kver }}-t2-questing.iso.00"
          new_link2 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/${{ matrix.target.image }}-25.10-${{ env.kver }}-t2-questing.iso.01"
          new_link3 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/${{ matrix.target.image }}-25.10-${{ env.kver }}-t2-questing.iso.02"
          # Load the JSON file
          with open('distro-metadata.json', 'r') as file:
              data = json.load(file)
          # Function to update the links
          def update_links(distros, name, new_links, sha256):
              for distro in distros:
                  if distro['name'] == name:
                      distro['iso'] = new_links
                      distro['sha256'] = sha256
          # Update the links
          update_links(data['all'], "${{ env.caps }} 25.10 - Questing Quokka", [new_link1, new_link2, new_link3], "${{ env.sha256 }}")
          # Save the updated JSON back to the file
          with open('distro-metadata.json', 'w') as file:
              json.dump(data, file, indent=2)
          print("Links updated successfully.")
          EOF

          python3 update.py
          rm update.py
          cd -

      - name: Push updated links to t2linux.org
        if: github.ref == 'refs/heads/mainline'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'wiki'
          destination-github-username: 't2linux'
          destination-repository-name: 'wiki'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: master
          commit-message: Distro metadata - Update ${{ env.caps }} 25.10 to v${{ env.isotag }}
