---
name: CI
# yamllint disable-line rule:truthy
on:
  [push, workflow_dispatch]

jobs:

  ISO:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: sudo ./build_in_docker.sh

      - name: print sha256sum
        run: cat output/sha256*

      - name: Generate Tag
        id: tag
        run: |
          VER=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          echo Version is $VER
          echo "kver=${VER}" >> $GITHUB_ENV
          echo "isotag=${VER}-${REL}" >> $GITHUB_ENV

      - name: Upload iso artifact
        uses: actions/upload-artifact@v6
        with:
          name: mbp-ubuntu-${{ steps.tag.outputs.tag }}.z01
          path: ${{ github.workspace }}/output/*

      - name: Instructions for putting it back together
        run: |
          cat << EOF
          Download all the artifacts, and put them in a folder
          without other files. Then run:"
          unzip "*.z??.zip"
          cat livecd-${{ env.isotag }}-t2.z?? > cd.zip
          echo unzip cd.zip
          EOF

      - name: Release
        if: github.ref == 'refs/heads/mainline'
        uses: softprops/action-gh-release@v2
        with:
          #files: ${{ github.workspace }}/ISO/*.tar.gz
          #files: ${{ github.workspace }}/ISO/*.iso
          files: ${{ github.workspace }}/output/*
          tag_name: v${{ env.isotag }}
          #body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the json
        if: github.ref == 'refs/heads/mainline'
        run: |
          git clone https://github.com/t2linux/wiki.git
          cd wiki/docs/tools

          cat << EOF > update.py
          import json
          # Define the new links
          new_link1 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-25.10-${{ env.kver }}-t2-questing.iso.00"
          new_link2 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-25.10-${{ env.kver }}-t2-questing.iso.01"
          new_link3 = "https://github.com/t2linux/T2-Ubuntu/releases/download/v${{ env.isotag }}/ubuntu-25.10-${{ env.kver }}-t2-questing.iso.02"
          # Load the JSON file
          with open('distro-metadata.json', 'r') as file:
              data = json.load(file)
          # Function to update the links
          def update_links(distros, name, new_links):
              for distro in distros:
                  if distro['name'] == name:
                      distro['iso'] = new_links
          # Update the links
          update_links(data['all'], "Ubuntu 25.10 - Questing Quokka", [new_link1, new_link2, new_link3])
          # Save the updated JSON back to the file
          with open('distro-metadata.json', 'w') as file:
              json.dump(data, file, indent=2)
          print("Links updated successfully.")
          EOF

          python3 update.py
          rm update.py
          cd -

      - name: Push updated links to t2linux.org
        if: github.ref == 'refs/heads/mainline'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'wiki'
          destination-github-username: 't2linux'
          destination-repository-name: 'wiki'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: master
          commit-message: Distro metadata - Update Ubuntu 25.10 to v${{ env.isotag }}
